### ISSUE TITLE
Failure running built in server on PHP 7.1.12

### ISSUE THREAD

**Issue by nullbtb** [InterNations/http-mock#39]
Encountered this on our travis builds today.  It seems there was a change to the web server logic on PHP 7.1.12.. may be a bug on their part.

+[Tue Nov 28 21:58:09 2017] PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
+[Tue Nov 28 21:58:09 2017] PHP Fatal error:  Unknown: Failed opening required '/home/travis/build/---/vendor/internations/http-mock/public/public/index.php' (include_path='.:/home/travis/.phpenv/versions/7.1.12/share/pear') in Unknown on line 0

As far as I can tell changing the command in the constructor for InterNations\Component\HttpMock\Server to:
'exec php -dalways_populate_raw_post_data=-1 -derror_log= -S %s -t public/ index.php', seems to fix it for my environment.

**Comment by EricTendian** [comment]
@nullbtb thanks for filing this issue and suggesting a solution! I'm getting the same thing. While your fix does work for 7.1.12, it doesn't seem to be backwards-compatible with PHP 7.1.11 due to the nature of the change. I've opened a PR https://github.com/InterNations/http-mock/pull/40 which describes the change PHP made and provides a backwards-compatible fix.

**Comment by kiproping** [comment]
Same here. 7.1.12 is definitely the culprit.

**Comment by ademarco** [comment]
Travis likes PR #41 which is based on @EricTendian 's #40 : @lstrojny can we merge#41 in? :)
